version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "80:80"
    environment:
      - STORAGE_NAME=fake_storage_name
      - STORAGE_ACCOUNT_KEY=fake_storage_key
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

#